#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon May  6 14:29:01 2019

@author: keziah
"""

import sys
import numpy as np

def print_stats_excl_0(array, name):
    s_funcs = {'Mean':np.mean, ' Med':np.median, '  SD':np.std}
    print(name.upper())
    for fname, func in s_funcs.items():
        print('{}: {:.3f}'.format(fname, func(array[1:])))
    print()
    
    
def print_stats(array, name):
    s_funcs = {'Mean':np.mean, ' Med':np.median, '  SD':np.std}
    print(name.upper())
    for fname, func in s_funcs.items():
        print('{}: {:.3f}'.format(fname, func(array)))
    print()
    
def get_stats():
    low_p = np.array([0, 82, 82.5967, 76.4706, 76.3871, 73.5577, 74.3119, 
                      89.5349, 84.6154])
    low_r = np.array([0, 44.086, 26.7921, 35.3064, 32.5454, 27.1277, 17.7632, 
                      10.5769, 16.6667])
    low_f = np.array([0, 57.3427, 40.4601, 48.3087, 45.6438, 39.6373, 28.6726, 
                      18.9189, 27.8481])

    high_p = np.array([0, 78.125, 55.1873, 55.8508, 78.0836, 70.354, 84.4311, 
                       89.5973, 88.4615])
    high_r = np.array([0, 53.7634, 34.319, 44.2201, 42.1111, 37.5887, 41.2281, 
                       36.6758, 34.8485])
    high_f = np.array([0, 63.6943, 42.3204, 50.497, 54.7143, 48.9985, 55.4028, 
                       52.0468, 50])
    
    stats_d = {'low damping, precision':low_p, 'low damping, recall':low_r, 
               'low damping, F-measure':low_f, 
               'high damping, precision':high_p, 'high damping, recall':high_r, 
               'high damping, F-measure':high_f}

    return stats_d

if __name__ == '__main__':
    
    sys.stdout = open('../results/Iowa/ocatves_analysis.txt', 'w')
    print('Low damping numbers from 4_Apr_3 and high damping from 6_Apr_2')
    print('This file is generated by {}'.format(__file__))
    print()
    
    stats_d = get_stats()
    
    s = 'ALL OCTAVES'
    print(s)
    print('-'*len(s))
    for s, stats in stats_d.items():
        print_stats(stats, s)
    print()
    
    s = 'OCTAVES 1-7'
    print(s)
    print('-'*len(s))
    for s, stats in stats_d.items():
        print_stats_excl_0(stats, s)
    
    
